---

    # 
  # 
  # ======== Result =========
  # 
  # best option name OPQ16,IVF16384,PQ16
  # nprobe: 14
  # QPS 5840.634125990822
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 264.0
  #         FF: 126674
  #         LUT: 98580
  #         DSP48E: 638
  #         
  # QPS: 5840.634125990822
  # Cycles per query: 23970
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 11
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 6.0
  #         URAM: 0
  #         FF: 8804.94
  #         LUT: 9374.58
  #         DSP48E: 0
  #         
  # QPS: 8532.423208191127
  # Cycles per query: 16408
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 169.0
  #         URAM: 280
  #         FF: 34703
  #         LUT: 25671
  #         DSP48E: 162
  #         
  # QPS: 6527.4151436031325
  # Cycles per query: 21448
  # PE_NUM_TABLE_CONSTRUCTION: 3
  # Stage 5:
  # 
  #         HBM_bank: 7.0
  #         BRAM_18K: 147.0
  #         URAM: 0.0
  #         FF: 41167.0
  #         LUT: 38299.333333333336
  #         DSP48E: 210.0
  #         
  # QPS: 6313.131313131313
  # Cycles per query: 22176
  # HBM_CHANNEL_NUM: 7
  # STAGE5_COMP_PE_NUM: 7
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 30.0
  #         URAM: 0
  #         FF: 296955.0
  #         LUT: 324855.0
  #         DSP48E: 0
  #         
  # QPS: 7906.03117235148
  # Cycles per query: 17708
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 7329604
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 7.0
  #         BRAM_18K: 1184.0
  #         URAM: 544.0
  #         FF: 1000661.94
  #         LUT: 781525.9133333333
  #         DSP48E: 1030.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 7.0
  #         BRAM_18K: 390.0
  #         URAM: 544.0
  #         FF: 510962.94
  #         LUT: 498931.91333333333
  #         DSP48E: 1030.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '7.070035460992907%', 'FF': '4.85832412862052%', 'LUT': '7.561671575846833%', 'URAM': '27.500000000000004%'}
  # Stage 3: {'BRAM_18K': '0.1488095238095238%', 'DSP48E': '0.0%', 'FF': '0.3376956001472754%', 'LUT': '0.7190859720176731%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '4.191468253968254%', 'DSP48E': '1.795212765957447%', 'FF': '1.330963119783996%', 'LUT': '1.9691181885125184%', 'URAM': '29.166666666666668%'}
  # Stage 5: {'BRAM_18K': '3.6458333333333335%', 'DSP48E': '2.327127659574468%', 'FF': '1.5788767182130583%', 'LUT': '2.9377863688430703%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '0.744047619047619%', 'DSP48E': '0.0%', 'FF': '11.38910622238586%', 'LUT': '24.91830817378498%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '9.487179487179487%', 'DSP48E': '1.9417475728155338%', 'FF': '0.5203899914933166%', 'LUT': '0.43132137722412284%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.43132137722412284%
  # Stage 2: {'BRAM_18K': '0.2564102564102564%', 'DSP48E': '61.94174757281553%', 'FF': '24.791230455970055%', 'LUT': '19.75820695481135%', 'URAM': '48.529411764705884%'}
  # LUT only:
  # Stage 2: 19.75820695481135%
  # Stage 3: {'BRAM_18K': '1.5384615384615385%', 'DSP48E': '0.0%', 'FF': '1.723205209364108%', 'LUT': '1.8789297195621364%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 1.8789297195621364%
  # Stage 4: {'BRAM_18K': '43.333333333333336%', 'DSP48E': '15.728155339805824%', 'FF': '6.791686301163055%', 'LUT': '5.145191019851513%', 'URAM': '51.470588235294116%'}
  # LUT only:
  # Stage 4: 5.145191019851513%
  # Stage 5: {'BRAM_18K': '37.69230769230769%', 'DSP48E': '20.388349514563107%', 'FF': '8.05674869492492%', 'LUT': '7.676264498187309%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 7.676264498187309%
  # Stage 6: {'BRAM_18K': '7.6923076923076925%', 'DSP48E': '0.0%', 'FF': '58.11673934708455%', 'LUT': '65.11008643036357%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 65.11008643036357%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '29.365079365079367%', 'DSP48E': '11.414007092198581%', 'FF': '38.378357418998526%', 'LUT': '59.947679900998196%', 'URAM': '56.666666666666664%'}


  # Constants
  NLIST: 16384
  NPROBE: 14
  D: 96
  M: 16
  K: 256
  TOPK: 100

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: True
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 11

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 3

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 7 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 7

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_NAME: Deep1000M
  DB_SCALE: 1000M # 1M to 1000M
  FPGA_NUM: 8 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U55C # Supported devices: U280, U250, U50
  FREQ: 140
