---

    # 
  # 
  # ======== Result =========
  # 
  # best option name IVF2048,PQ16
  # nprobe: 2
  # QPS 31876.138433515483
  # stage_option_list
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 64.0
  #         FF: 92159
  #         LUT: 71742
  #         DSP48E: 464
  #         
  # QPS: 33065.658951346246
  # Cycles per query: 4234
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 8
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 0
  #         FF: 487.14
  #         LUT: 484.98
  #         DSP48E: 0
  #         
  # QPS: 34079.84420642648
  # Cycles per query: 4108
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 1
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 1
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 54.0
  #         URAM: 48
  #         FF: 17562
  #         LUT: 13946
  #         DSP48E: 108
  #         
  # QPS: 31876.138433515483
  # Cycles per query: 4392
  # PE_NUM_TABLE_CONSTRUCTION: 2
  # Stage 5:
  # 
  #         HBM_bank: 13.0
  #         BRAM_18K: 819.0
  #         URAM: 0.0
  #         FF: 229359.0
  #         LUT: 213382.0
  #         DSP48E: 1170.0
  #         
  # QPS: 33034.450212364325
  # Cycles per query: 4238
  # HBM_CHANNEL_NUM: 13
  # STAGE5_COMP_PE_NUM: 39
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 158.0
  #         URAM: 0
  #         FF: 30499.53
  #         LUT: 25555.71
  #         DSP48E: 0
  #         
  # QPS: 39648.82469555367
  # Cycles per query: 3531
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 38188209
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 13.0
  #         BRAM_18K: 1827.0
  #         URAM: 112.0
  #         FF: 859765.67
  #         LUT: 607704.69
  #         DSP48E: 1742.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 13.0
  #         BRAM_18K: 1033.0
  #         URAM: 112.0
  #         FF: 370066.67000000004
  #         LUT: 325110.69
  #         DSP48E: 1742.0
  #         
  # Per Stage Utilization rate (Total = FPGA):
  # 
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '5.141843971631205%', 'FF': '3.5345713672066763%', 'LUT': '5.503037555228277%', 'URAM': '6.666666666666667%'}
  # Stage 3: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '0.0%', 'FF': '0.018683265832106038%', 'LUT': '0.0372008468335788%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '1.3392857142857142%', 'DSP48E': '1.196808510638298%', 'FF': '0.6735548600883653%', 'LUT': '1.0697410407461954%', 'URAM': '5.0%'}
  # Stage 5: {'BRAM_18K': '20.3125%', 'DSP48E': '12.965425531914892%', 'FF': '8.796598858615612%', 'LUT': '16.367666912125674%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '3.9186507936507935%', 'DSP48E': '0.0%', 'FF': '1.1697475607511045%', 'LUT': '1.9602747606774669%', 'URAM': '0.0%'}
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # 
  # Stage 2: {'BRAM_18K': '0.0968054211035818%', 'DSP48E': '26.63605051664753%', 'FF': '24.903350523298947%', 'LUT': '22.06694587618758%', 'URAM': '57.14285714285714%'}
  # LUT only:
  # Stage 2: 22.06694587618758%
  # Stage 3: {'BRAM_18K': '0.0968054211035818%', 'DSP48E': '0.0%', 'FF': '0.13163574012217852%', 'LUT': '0.14917380908022435%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 0.14917380908022435%
  # Stage 4: {'BRAM_18K': '5.227492739593417%', 'DSP48E': '6.199770378874857%', 'FF': '4.745631375016831%', 'LUT': '4.289615945879848%', 'URAM': '42.857142857142854%'}
  # LUT only:
  # Stage 4: 4.289615945879848%
  # Stage 5: {'BRAM_18K': '79.28363988383349%', 'DSP48E': '67.16417910447761%', 'FF': '61.97775119818274%', 'LUT': '65.63364618985614%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 65.63364618985614%
  # Stage 6: {'BRAM_18K': '15.295256534365926%', 'DSP48E': '0.0%', 'FF': '8.24163116337929%', 'LUT': '7.860618178996205%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 7.860618178996205%
  # Total Utilization rate:
  # {'BRAM_18K': '45.3125%', 'DSP48E': '19.304078014184398%', 'FF': '32.97456699496809%', 'LUT': '46.6145595544919%', 'URAM': '11.666666666666666%'}


  # Constants
  NLIST: 2048
  NPROBE: 2
  D: 96
  M: 16
  K: 256
  TOPK: 1

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: False
  OPQ_UNROLL_FACTOR: <--OPQ_unroll_factor--> # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 8

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 1 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 1 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 2

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 13 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 39

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_NAME: Deep1000M
  DB_SCALE: 1000M # 1M to 1000M
  FPGA_NUM: 8 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U55C # Supported devices: U280, U250, U50
  FREQ: 140
