---

    # 
  # 
  # ======== Result =========
  # 
  # best option name OPQ16,IVF16384,PQ16
  # nprobe: 34
  # QPS 2376.0225382709345
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 280.0
  #         FF: 57644
  #         LUT: 44904
  #         DSP48E: 290
  #         
  # QPS: 2663.217166336935
  # Cycles per query: 52568
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 5
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 0
  #         FF: 6761.38
  #         LUT: 7380.66
  #         DSP48E: 0
  #         
  # QPS: 4266.7316835304155
  # Cycles per query: 32812
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 1
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 1
  # Stage 4:
  # 
  #         HBM_bank: 1
  #         BRAM_18K: 361.0
  #         URAM: 24
  #         FF: 52943
  #         LUT: 36039
  #         DSP48E: 162
  #         
  # QPS: 2729.2576419213974
  # Cycles per query: 51296
  # PE_NUM_TABLE_CONSTRUCTION: 3
  # Stage 5:
  # 
  #         HBM_bank: 5.0
  #         BRAM_18K: 105.0
  #         URAM: 0.0
  #         FF: 29405.0
  #         LUT: 27356.666666666668
  #         DSP48E: 150.0
  #         
  # QPS: 2376.0225382709345
  # Cycles per query: 58922
  # HBM_CHANNEL_NUM: 5
  # STAGE5_COMP_PE_NUM: 5
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 22.0
  #         URAM: 0
  #         FF: 217767.0
  #         LUT: 238227.0
  #         DSP48E: 0
  #         
  # QPS: 2917.760826976783
  # Cycles per query: 47982
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 2557572
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 6.0
  #         BRAM_18K: 1321.0
  #         URAM: 304.0
  #         FF: 856878.38
  #         LUT: 638653.3266666667
  #         DSP48E: 622.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 6.0
  #         BRAM_18K: 527.0
  #         URAM: 304.0
  #         FF: 367179.38
  #         LUT: 356059.32666666666
  #         DSP48E: 622.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '3.2136524822695036%', 'FF': '2.2108186057928325%', 'LUT': '3.4444035346097204%', 'URAM': '29.166666666666668%'}
  # Stage 3: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '0.0%', 'FF': '0.25931900466372115%', 'LUT': '0.5661404639175258%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '8.953373015873016%', 'DSP48E': '1.795212765957447%', 'FF': '2.0305212935689743%', 'LUT': '2.7644053755522826%', 'URAM': '2.5%'}
  # Stage 5: {'BRAM_18K': '2.604166666666667%', 'DSP48E': '1.6622340425531914%', 'FF': '1.127769084437899%', 'LUT': '2.0984188348879074%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '0.5456349206349206%', 'DSP48E': '0.0%', 'FF': '8.352011229749632%', 'LUT': '18.273425994108983%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '7.020872865275142%', 'DSP48E': '3.215434083601286%', 'FF': '0.7241692057979944%', 'LUT': '0.6043936610638613%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.6043936610638613%
  # Stage 2: {'BRAM_18K': '0.18975332068311196%', 'DSP48E': '46.62379421221865%', 'FF': '15.699138660782094%', 'LUT': '12.611381485321388%', 'URAM': '92.10526315789474%'}
  # LUT only:
  # Stage 2: 12.611381485321388%
  # Stage 3: {'BRAM_18K': '0.18975332068311196%', 'DSP48E': '0.0%', 'FF': '1.8414378280174666%', 'LUT': '2.0728736609979546%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 2.0728736609979546%
  # Stage 4: {'BRAM_18K': '68.50094876660341%', 'DSP48E': '26.04501607717042%', 'FF': '14.41883800773344%', 'LUT': '10.12162785830878%', 'URAM': '7.894736842105263%'}
  # LUT only:
  # Stage 4: 10.12162785830878%
  # Stage 5: {'BRAM_18K': '19.924098671726757%', 'DSP48E': '24.115755627009648%', 'FF': '8.008347309699145%', 'LUT': '7.68317654329478%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 7.68317654329478%
  # Stage 6: {'BRAM_18K': '4.174573055028463%', 'DSP48E': '0.0%', 'FF': '59.308068987969854%', 'LUT': '66.90654679101323%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 66.90654679101323%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '32.76289682539682%', 'DSP48E': '6.892730496453901%', 'FF': '32.86383084806088%', 'LUT': '48.98850382506954%', 'URAM': '31.666666666666664%'}


  # Constants
  NLIST: 16384
  NPROBE: 34
  D: 96
  M: 16
  K: 256
  TOPK: 100

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: True
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 5

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 1 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 1 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 3

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 5 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 5

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_NAME: Deep100M
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U55C # Supported devices: U280, U250, U50
  FREQ: 140
