---

    # 
  # 
  # ======== Result =========
  # 
  # best option name OPQ16,IVF8192,PQ16
  # nprobe: 6
  # QPS 12477.718360071302
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 192.0
  #         FF: 138179
  #         LUT: 107526
  #         DSP48E: 696
  #         
  # QPS: 12655.939251491593
  # Cycles per query: 11062
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 12
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 6.0
  #         URAM: 0
  #         FF: 4099.26
  #         LUT: 4202.82
  #         DSP48E: 0
  #         
  # QPS: 17056.53021442495
  # Cycles per query: 8208
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 121.0
  #         URAM: 152
  #         FF: 30143
  #         LUT: 23079
  #         DSP48E: 162
  #         
  # QPS: 16173.752310536043
  # Cycles per query: 8656
  # PE_NUM_TABLE_CONSTRUCTION: 3
  # Stage 5:
  # 
  #         HBM_bank: 9.0
  #         BRAM_18K: 189.0
  #         URAM: 0.0
  #         FF: 52929.0
  #         LUT: 49242.0
  #         DSP48E: 270.0
  #         
  # QPS: 12477.718360071302
  # Cycles per query: 11220
  # HBM_CHANNEL_NUM: 9
  # STAGE5_COMP_PE_NUM: 9
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 38.0
  #         URAM: 0
  #         FF: 40863.299999999996
  #         LUT: 42995.1
  #         DSP48E: 0
  #         
  # QPS: 15109.0006475286
  # Cycles per query: 9266
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 4672846
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 9.0
  #         BRAM_18K: 1186.0
  #         URAM: 344.0
  #         FF: 758571.56
  #         LUT: 511790.92000000004
  #         DSP48E: 1148.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 9.0
  #         BRAM_18K: 392.0
  #         URAM: 344.0
  #         FF: 268872.56
  #         LUT: 229196.92
  #         DSP48E: 1148.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '7.712765957446808%', 'FF': '5.299575049091802%', 'LUT': '8.247882916053019%', 'URAM': '20.0%'}
  # Stage 3: {'BRAM_18K': '0.1488095238095238%', 'DSP48E': '0.0%', 'FF': '0.15721879602356406%', 'LUT': '0.3223812592047128%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '3.0009920634920637%', 'DSP48E': '1.795212765957447%', 'FF': '1.1560735763377517%', 'LUT': '1.7702963917525774%', 'URAM': '15.833333333333332%'}
  # Stage 5: {'BRAM_18K': '4.6875%', 'DSP48E': '2.992021276595745%', 'FF': '2.029984351988218%', 'LUT': '3.7771539027982324%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '0.9424603174603174%', 'DSP48E': '0.0%', 'FF': '1.567228921207658%', 'LUT': '3.2979795655375552%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '9.438775510204081%', 'DSP48E': '1.7421602787456445%', 'FF': '0.9889443534141231%', 'LUT': '0.9389305929591026%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.9389305929591026%
  # Stage 2: {'BRAM_18K': '0.25510204081632654%', 'DSP48E': '60.62717770034843%', 'FF': '51.39200519383606%', 'LUT': '46.914243001171215%', 'URAM': '55.81395348837209%'}
  # LUT only:
  # Stage 2: 46.914243001171215%
  # Stage 3: {'BRAM_18K': '1.530612244897959%', 'DSP48E': '0.0%', 'FF': '1.524610767272049%', 'LUT': '1.8337157410317728%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 1.8337157410317728%
  # Stage 4: {'BRAM_18K': '30.86734693877551%', 'DSP48E': '14.111498257839722%', 'FF': '11.210887418188008%', 'LUT': '10.069507042241229%', 'URAM': '44.18604651162791%'}
  # LUT only:
  # Stage 4: 10.069507042241229%
  # Stage 5: {'BRAM_18K': '48.214285714285715%', 'DSP48E': '23.519163763066203%', 'FF': '19.685534291784926%', 'LUT': '21.484581904503777%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 21.484581904503777%
  # Stage 6: {'BRAM_18K': '9.693877551020408%', 'DSP48E': '0.0%', 'FF': '15.198017975504824%', 'LUT': '18.759021718092896%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 18.759021718092896%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '29.41468253968254%', 'DSP48E': '12.72163120567376%', 'FF': '29.093472324496812%', 'LUT': '39.25740365733923%', 'URAM': '35.833333333333336%'}


  # Constants
  NLIST: 8192
  NPROBE: 6
  D: 96
  M: 16
  K: 256
  TOPK: 10

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: True
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 12

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 3

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 9 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 9

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_NAME: Deep100M
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U55C # Supported devices: U280, U250, U50
  FREQ: 140
