---

    # 
  # 
  # ======== Result =========
  # 
  # best option name OPQ16,IVF16384,PQ16
  # nprobe: 33
  # QPS 3182.6138352770013
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 288.0
  #         FF: 69149
  #         LUT: 53850
  #         DSP48E: 348
  #         
  # QPS: 3194.159251654118
  # Cycles per query: 43830
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 6
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 0
  #         FF: 6565.3099999999995
  #         LUT: 7165.17
  #         DSP48E: 0
  #         
  # QPS: 4266.8617232025845
  # Cycles per query: 32811
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 1
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 1
  # Stage 4:
  # 
  #         HBM_bank: 1
  #         BRAM_18K: 348.0
  #         URAM: 32
  #         FF: 57924
  #         LUT: 40852
  #         DSP48E: 216
  #         
  # QPS: 3635.985871597756
  # Cycles per query: 38504
  # PE_NUM_TABLE_CONSTRUCTION: 4
  # Stage 5:
  # 
  #         HBM_bank: 7.0
  #         BRAM_18K: 147.0
  #         URAM: 0.0
  #         FF: 41167.0
  #         LUT: 38299.333333333336
  #         DSP48E: 210.0
  #         
  # QPS: 3182.6138352770013
  # Cycles per query: 43989
  # HBM_CHANNEL_NUM: 7
  # STAGE5_COMP_PE_NUM: 7
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 30.0
  #         URAM: 0
  #         FF: 296955.0
  #         LUT: 324855.0
  #         DSP48E: 0
  #         
  # QPS: 4203.194427765102
  # Cycles per query: 33308
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 5814366
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 8.0
  #         BRAM_18K: 1358.0
  #         URAM: 320.0
  #         FF: 964118.31
  #         LUT: 749767.5033333333
  #         DSP48E: 794.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 8.0
  #         BRAM_18K: 564.0
  #         URAM: 320.0
  #         FF: 474419.31
  #         LUT: 467173.5033333333
  #         DSP48E: 794.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '3.856382978723404%', 'FF': '2.6520695262641136%', 'LUT': '4.1306148748159055%', 'URAM': '30.0%'}
  # Stage 3: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '0.0%', 'FF': '0.25179913782523317%', 'LUT': '0.5496111008836524%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '8.630952380952381%', 'DSP48E': '2.393617021276596%', 'FF': '2.2215574374079528%', 'LUT': '3.133591065292096%', 'URAM': '3.3333333333333335%'}
  # Stage 5: {'BRAM_18K': '3.6458333333333335%', 'DSP48E': '2.327127659574468%', 'FF': '1.5788767182130583%', 'LUT': '2.9377863688430703%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '0.744047619047619%', 'DSP48E': '0.0%', 'FF': '11.38910622238586%', 'LUT': '24.91830817378498%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '6.560283687943262%', 'DSP48E': '2.518891687657431%', 'FF': '0.56047465690214%', 'LUT': '0.4606425631259581%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.4606425631259581%
  # Stage 2: {'BRAM_18K': '0.1773049645390071%', 'DSP48E': '43.8287153652393%', 'FF': '14.57550283946073%', 'LUT': '11.52676673993162%', 'URAM': '90.0%'}
  # LUT only:
  # Stage 2: 11.52676673993162%
  # Stage 3: {'BRAM_18K': '0.1773049645390071%', 'DSP48E': '0.0%', 'FF': '1.3838623052674648%', 'LUT': '1.5337278225061437%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 1.5337278225061437%
  # Stage 4: {'BRAM_18K': '61.702127659574465%', 'DSP48E': '27.204030226700255%', 'FF': '12.209452435652334%', 'LUT': '8.744502782909686%', 'URAM': '10.0%'}
  # LUT only:
  # Stage 4: 8.744502782909686%
  # Stage 5: {'BRAM_18K': '26.063829787234045%', 'DSP48E': '26.448362720403022%', 'FF': '8.677344941967055%', 'LUT': '8.198096223365296%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 8.198096223365296%
  # Stage 6: {'BRAM_18K': '5.319148936170213%', 'DSP48E': '0.0%', 'FF': '62.59336282075027%', 'LUT': '69.53626386816131%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 69.53626386816131%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '33.68055555555556%', 'DSP48E': '8.798758865248226%', 'FF': '36.97680067194404%', 'LUT': '57.511621205612826%', 'URAM': '33.33333333333333%'}


  # Constants
  NLIST: 16384
  NPROBE: 33
  D: 128
  M: 16
  K: 256
  TOPK: 100

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: True
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 6

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 1 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 1 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 4

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 7 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 7

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_NAME: SIFT100M
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U55C # Supported devices: U280, U250, U50
  FREQ: 140
