---

    # 
  # 
  # ======== Result =========
  # 
  # best option name OPQ16,IVF4096,PQ16
  # nprobe: 6
  # QPS 18459.915611814347
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 72.0
  #         FF: 103664
  #         LUT: 80688
  #         DSP48E: 522
  #         
  # QPS: 18867.924528301886
  # Cycles per query: 7420
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 9
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 6.0
  #         URAM: 0
  #         FF: 4099.26
  #         LUT: 4202.82
  #         DSP48E: 0
  #         
  # QPS: 34046.69260700389
  # Cycles per query: 4112
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 130.0
  #         URAM: 112
  #         FF: 49646
  #         LUT: 40110
  #         DSP48E: 324
  #         
  # QPS: 31876.138433515483
  # Cycles per query: 4392
  # PE_NUM_TABLE_CONSTRUCTION: 6
  # Stage 5:
  # 
  #         HBM_bank: 10.0
  #         BRAM_18K: 630.0
  #         URAM: 0.0
  #         FF: 176430.0
  #         LUT: 164140.0
  #         DSP48E: 900.0
  #         
  # QPS: 18459.915611814347
  # Cycles per query: 7584
  # HBM_CHANNEL_NUM: 10
  # STAGE5_COMP_PE_NUM: 30
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 2.0
  #         URAM: 0
  #         FF: 83156.7
  #         LUT: 77874.9
  #         DSP48E: 0
  #         
  # QPS: 25528.81108679796
  # Cycles per query: 5484
  # 
  # SORT_GROUP_ENABLE: True
  # SORT_GROUP_NUM: 2
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 13167140
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 10.0
  #         BRAM_18K: 1600.0
  #         URAM: 184.0
  #         FF: 909353.96
  #         LUT: 651761.72
  #         DSP48E: 1766.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 10.0
  #         BRAM_18K: 806.0
  #         URAM: 184.0
  #         FF: 419654.96
  #         LUT: 369167.72
  #         DSP48E: 1766.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '5.784574468085106%', 'FF': '3.9758222876779574%', 'LUT': '6.189248895434463%', 'URAM': '7.5%'}
  # Stage 3: {'BRAM_18K': '0.1488095238095238%', 'DSP48E': '0.0%', 'FF': '0.15721879602356406%', 'LUT': '0.3223812592047128%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '3.2242063492063497%', 'DSP48E': '3.590425531914894%', 'FF': '1.9040715513009325%', 'LUT': '3.076675257731959%', 'URAM': '11.666666666666666%'}
  # Stage 5: {'BRAM_18K': '15.625%', 'DSP48E': '9.97340425531915%', 'FF': '6.766614506627393%', 'LUT': '12.590513009327442%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '0.0496031746031746%', 'DSP48E': '0.0%', 'FF': '3.1893064248895433%', 'LUT': '5.973467415316642%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '4.590570719602978%', 'DSP48E': '1.1325028312570782%', 'FF': '0.6336157685351794%', 'LUT': '0.5829328739793393%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.5829328739793393%
  # Stage 2: {'BRAM_18K': '0.12406947890818859%', 'DSP48E': '29.55832389580974%', 'FF': '24.702198205878467%', 'LUT': '21.85673221916586%', 'URAM': '39.130434782608695%'}
  # LUT only:
  # Stage 2: 21.85673221916586%
  # Stage 3: {'BRAM_18K': '0.7444168734491315%', 'DSP48E': '0.0%', 'FF': '0.9768167639434073%', 'LUT': '1.1384581512164715%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 1.1384581512164715%
  # Stage 4: {'BRAM_18K': '16.129032258064516%', 'DSP48E': '18.346545866364668%', 'FF': '11.830194977321367%', 'LUT': '10.864980285925325%', 'URAM': '60.86956521739131%'}
  # LUT only:
  # Stage 4: 10.864980285925325%
  # Stage 5: {'BRAM_18K': '78.16377171215882%', 'DSP48E': '50.962627406568515%', 'FF': '42.04168109915822%', 'LUT': '44.46217562033864%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 44.46217562033864%
  # Stage 6: {'BRAM_18K': '0.24813895781637718%', 'DSP48E': '0.0%', 'FF': '19.81549318516335%', 'LUT': '21.094720849374372%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 21.094720849374372%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '39.682539682539684%', 'DSP48E': '19.57003546099291%', 'FF': '34.87642519636721%', 'LUT': '49.993995459008346%', 'URAM': '19.166666666666668%'}


  # Constants
  NLIST: 4096
  NPROBE: 6
  D: 96
  M: 16
  K: 256
  TOPK: 10

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: True
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 9

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 6

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 10 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 30

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: True
  SORT_GROUP_NUM: 2 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_NAME: Deep100M
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U55C # Supported devices: U280, U250, U50
  FREQ: 140
